#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $DIR/az-functions

delete_all_resource_groups() {
    names=($(az group list | jq '.[].name'))
    for name in "${names[@]}"
    do
        cmd="az group delete --name $name --yes --verbose"
        echo $cmd
        sh -c "$cmd"
    done
}

read -p "Are you sure? [y|n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    delete_all_resource_groups
fi
