#!/usr/bin/env python3

import subprocess
import json

# az group create --name "group01" --location eastus
# tenant_id=$(az account show | jq '.tenantId')
# signed_in_user_details=$(az ad signed-in-user show | jq '.')

def sh(cmd):
    output = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE)
    return output.stdout.decode('utf-8')

def get_all_resource_group_names():
    cmd = "az group list | jq '.[].name'"
    output_string=sh(cmd)
    return output_string.split()

def cmd_to_json(cmd):
    output=sh(cmd)
    return json.loads(output)

def get_signed_in_user_details():
    cmd="az ad signed-in-user show"
    return cmd_to_json(cmd)

cmd = "az ad signed-in-user show | jq '.'"
#print(sh(cmd))

#print(get_all_resource_group_names()[0])
print(json.dumps(get_signed_in_user_details(), indent=4))
